# Generated by Django 4.1.4 on 2022-12-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedIn_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='%Y/%m/'),
        ),
    ]
